version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000" # Port ที่ expose สำหรับ backend
    env_file:
      - .env # ดึง environment variables จากไฟล์ .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest # ดึง MongoDB image จาก Docker Hub
    ports:
      - "27017:27017" # Port ของ MongoDB
    volumes:
      - mongo-data:/data/db # เก็บข้อมูลของ MongoDB บน host

volumes:
  mongo-data:
